IBM-only: Temporary workaround for gpfs.pm-ganesha dependency issue
..
libutil.so.1()(64bit)
nfs-ganesha >= 2.3.2-0 -----> wrong package name
rpmlib(CompressedFileNames) <= 3.0.4-1
..

The gpfs.pm-ganesha package incorrectly lists nfs-ganesha >= 2.3.2-0 as a dependency.
The correct dependency should be gpfs.nfs-ganesha.

$ rpm -qR  gpfs.pm-ganesha-10.0.0-2.el8.x86_64
...
libutil.so.1()(64bit)
nfs-ganesha >= 2.3.2-0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
...

This has worked so far due to a workaround or legacy code in the nfs-ganesha package.
For now, a similar temporary hack will be applied to maintain compatibility.

Without this fix, the Ganesha upgrade will fail with the following error:

$ rpm -Uvh gpfs.nfs-ganesha-7.0-ibm001.02.el8.x86_64.rpm
	gpfs.nfs-ganesha-gpfs-7.0-ibm001.02.el8.x86_64.rpm \
	gpfs.nfs-ganesha-utils-7.0-ibm001.02.el8.x86_64.rpm
error: Failed dependencies:
	nfs-ganesha >= 2.3.2-0 is
	needed by (installed) gpfs.pm-ganesha-10.0.0-2.el8.x86_64

Change-Id: I0ef518250c9086966f8c0b76a8fb897e891e11e2
Signed-off-by: Prabhu Murugesan <prabhu.murugesan1@ibm.com>