ganesha_mgr:Fix show exports/clients "IndexError:"
$ ganesha_mgr show exports
Show exports
Traceback (most recent call last):
  File "/usr/bin/ganesha_mgr", line 470, in <module>
    exportmgr.showexports()
  File "/usr/bin/ganesha_mgr", line 92, in showexports
    status, msg, reply = self.exportmgr.ShowExports()
  File "/usr/lib/python3.6/site-packages/Ganesha/ganesha_mgr_utils.py", line 223, in ShowExports
    lasttime = ex[10]
IndexError: tuple index out of range
$ ganesha_mgr show clients
Show clients
Traceback (most recent call last):
  File "/usr/bin/ganesha_mgr", line 466, in <module>
    clientmgr.showclients()
  File "/usr/bin/ganesha_mgr", line 56, in showclients
    status, errormsg, reply = self.clientmgr.ShowClients()
  File "/usr/lib/python3.6/site-packages/Ganesha/ganesha_mgr_utils.py", line 94, in ShowClients
    lasttime = cl_[9]
IndexError: tuple index out of range

This is regression of commit id :0c1047500d2.

commit id : 0c1047500d2 has changed format of show exports[clints]
return value in server_stats_summary()

Signed-off-by: Prabhu Murugesan <skmprabhu2@gmail.com>
Change-Id: I173271b8395a4314f5e27fb4f9e7849aef9c5f99